# Generated by Django 2.0.2 on 2019-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('date', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('creator', models.TextField()),
                ('publication', models.CharField(max_length=500)),
                ('citation', models.TextField()),
            ],
        ),
    ]
